// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW2gQvAZ8ZUmsIXA9PSyFh032fWUX19x8',
    appId: '1:22024792739:web:c8a883bdcc4fafc816ad16',
    messagingSenderId: '22024792739',
    projectId: 'task-champ-ex9kwk',
    authDomain: 'task-champ-ex9kwk.firebaseapp.com',
    storageBucket: 'task-champ-ex9kwk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstU1gj00gNjyiZF2narjiQxG6tDmE4RI',
    appId: '1:22024792739:android:25da1732cb03be5f16ad16',
    messagingSenderId: '22024792739',
    projectId: 'task-champ-ex9kwk',
    storageBucket: 'task-champ-ex9kwk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfEgJrPrdaydTIBoIehSR6eRbjmKzy5lY',
    appId: '1:22024792739:ios:b6c74cac10a12fe016ad16',
    messagingSenderId: '22024792739',
    projectId: 'task-champ-ex9kwk',
    storageBucket: 'task-champ-ex9kwk.firebasestorage.app',
    iosBundleId: 'com.umanghirani.taskchamp',
  );

}